### ISSUE TITLE
Outdated python tutorial for the VOT toolkit

### ISSUE THREAD

**Issue by nvbln** [votchallenge/vot-website#2]
The python tutorial on the VOT website for the toolkit is outdated. On the website (and in the file: https://github.com/votchallenge/website/blob/8ec1d65f3b8a8b8c0d9fb553ac8d20ac75ca41dd/contents/howto/tutorial_python.md) the argument 'workspace' is used but this has since been renamed to 'initialize' (see https://github.com/votchallenge/toolkit/commit/c6f616b7b00e44e30562a225fa3702b4730d84e0).

**Comment by lukacu** [comment]
Thanks, updated!
